### PR TITLE
Use ruff --check because ruff suggests it

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by Vipitis** [comment]
I think it needs to be `ruff check .`  it took me a few commits to get right too

**Comment by hmaarrfk** [comment]
of course.. but now it finds an error locally. hoping i have my local environment misconfigured to pass the CIs.

**Comment by Vipitis** [comment]
I think there are some rule changes in ruff that require one or two changes, but I that is already included in #30 and completely unrelated to the original change your proposed. feels a bit like https://edw519.posthaven.com/it-takes-6-days-to-change-1-line-of-code

**Comment by hmaarrfk** [comment]
Yeah you went about it a different way than I did.
https://github.com/pygfx/shadertoy/pull/30/files#diff-b29c89baf4e736d8da5743808d8a6f2485125dba8cde0cef3c58a34843d2ff6eR156

**Comment by hmaarrfk** [comment]
the reason i chose my strategy is that lists and tuples are often not guaranteed:

```python
>>> [] == ()
False
```

**Comment by Vipitis** [comment]
> the reason i chose my strategy is that lists and tuples are often not guaranteed:
> 
> ```python
> >>> [] == ()
> False
> ```

json can't hold tuple, it mangles them to a list. But I have used that function with dicts before so I it's a good solution.
the CI doesn't yet run the API tests (we don't have a key set as repository secret) - but I confirmed it to work as expected locally.

**Review by Vipitis — APPROVED** [review]

**Pull request merged**
