### PR TITLE
Update wgpu dependency to match pygfx

### PR DESCRIPTION
**Pull request by hmaarrfk**
I tried examples/shadertoy_glsl_sdf.py it worked as well as a few others from that directory

### CODE REVIEW

**Comment by Vipitis** [comment]
I also have this in #30 but going directly to 0.16 as there is one change needed in the testutils see: https://github.com/pygfx/shadertoy/pull/30/commits/6e67f7e7ad7fcc918392e4b022da22a2f78b3950

what is the cure solution for pygfx regarding this change and support 0.15. as well?

**Comment by Korijn** [comment]
I think the code picks the method to call based on `wgpu.__version__`

**Comment by hmaarrfk** [comment]
The current problem I'm trying to address is that if you try to co-install this with the latest version of pygfx they require different versions and there isn't any intersection. 

I was hoping this would be a one line fix but I understand if there are other priorities that would create a conflict!

**Comment by Vipitis** [comment]
I think wgpu 0.15 is fine to use, just 0.16 is needed for CI. Maybe if we use different requirements for the dev option while allowing broader wgpu-py versions for runtime deps. Maybe like https://github.com/pygfx/pygfx/pull/786 pip might complain but nothing happens.

since v0.20 never released for wgpu-native and we already have wgpu-core releasing 22.0 I hope that a jump to wgpu 22 reaches wgpu-py soonish since a bunch of interesting stuff is in there that will be useful for shadertoy

**Comment by Korijn** [comment]
https://github.com/pygfx/pygfx/blob/eaf8acd4e4188b8f32302413984829b86497bf1f/pygfx/renderers/wgpu/engine/shared.py#L270-L274

**Comment by hmaarrfk** [comment]
@Vipitis i've reverted my changes, cherry-picked yours, and fixed it a little bit.

I think having 0.15.1 compatibility in the test suite is only going to hurt maintenance given the limited resources we all have ;)

**Comment by hmaarrfk** [comment]
Thank you whoever triggered the job.

CI failured being addressed in https://github.com/pygfx/shadertoy/pull/33

**Review by Vipitis — APPROVED** [review]

**Pull request merged**
